"""
Official NYC DOB complaint category codes -> human-readable descriptions.
"""

COMPLAINT_CATEGORY_LABELS = {
    "1": "Accident (Construction/Plumbing)",
    "2": "Accident (To Public)",
    "3": "Adjacent buildings not protected",
    "4": "Illegal after-hours work",
    "5": "No permit",
    "6": "Illegal grade/watercourse change",
    "7": "Illegal watercourse change",
    "8": "No contractor's sign",
    "9": "Excessive debris",
    "10": "Debris/building falling or in danger of falling",
    "11": "Demolition with no permit",
    "12": "Unsafe/illegal demolition",
    "13": "Elevator not FDNY-ready",
    "14": "Excavation undermining adjacent building",
    "15": "Fence missing/inadequate/illegal",
    "16": "Inadequate support/shoring",
    "17": "Hoist with no permit",
    "18": "Unsafe material storage",
    "19": "Illegal mechanical demolition",
    "20": "Illegal work on landmark building",
    "21": "Safety net/guard rail damaged or missing (6+ stories)",
    "22": "Missing safety netting",
    "23": "Sidewalk shed/scaffold defect or missing permit",
    "24": "Sidewalk shed missing",
    "25": "Missing warning signs/lights",
    "26": "No watchman",
    "27": "Illegal auto repair",
    "28": "Building in danger of collapse",
    "29": "Vacant, open and unguarded building",
    "30": "Building shaking/vibrating, structural stability affected",
    "31": "No/illegal Certificate of Occupancy",
    "32": "Not complying with Certificate of Occupancy",
    "33": "Illegal commercial use",
    "34": "Illegal compactor room/refuse chute",
    "35": "Illegal curb cut/driveway/carport",
    "36": "Illegal driveway/carport",
    "37": "Egress locked/blocked/improper",
    "38": "Exit door not proper",
    "39": "No secondary means of egress",
    "40": "Falling part of building",
    "41": "Part of building in danger of falling",
    "42": "Illegal fence",
    "43": "Structural stability affected",
    "44": "Illegal fireplace/wood stove",
    "45": "Illegal conversion",
    "46": "No PA (Place of Assembly) permit",
    "47": "Not complying with PA permit",
    "48": "Illegal residential use",
    "49": "Illegal storefront/sign/awning/marquee/canopy",
    "50": "Illegal sign erection/display in progress",
    "51": "Illegal social club",
    "52": "Inadequate sprinkler system",
    "53": "Illegal/improper vent or exhaust",
    "54": "Wall/retaining wall bulging or cracked",
    "55": "Non-conforming zoning",
    "56": "Boiler fumes/smoke/carbon monoxide",
    "57": "Illegal boiler",
    "58": "Defective/inoperative boiler, no permit",
    "59": "Defective/exposed electrical wiring (in progress)",
    "60": "Improper electrical work",
    "61": "Unlicensed electrical work in progress",
    "62": "Elevator danger condition / open shaft",
    "63": "Defective/inoperative elevator",
    "64": "Open and unguarded elevator shaft",
    "65": "Illegal or defective gas hookup/piping",
    "66": "Illegal plumbing work / no permit",
    "67": "Crane with no permit/license, unsafe or illegal",
    "68": "Unsafe/illegal crane or scaffold operations",
    "69": "Unsafe crane/scaffold installation or equipment",
    "70": "Suspension scaffold hanging with no work in progress",
    "71": "Illegal SRO work / no permit / change of use",
    "72": "SRO change of occupancy/use",
    "73": "Failure to maintain",
    "74": "Illegal commercial/manufacturing use in residential zone",
    "75": "Adult establishment",
    "76": "Unlicensed/illegal plumbing work in progress",
    "77": "Non-compliant with handicap access law",
    "78": "Privately owned public space non-compliance",
    "79": "Parking lot lights shining on building",
    "80": "Elevator not inspected / illegal / no permit",
    "81": "Elevator accident",
    "82": "Boiler accident/explosion",
    "83": "Construction beyond approved plans/permits",
    "84": "Defective/cracking facade",
    "85": "Improper drainage",
    "86": "Work contrary to stop work order",
    "87": "Deck safety inspection requested",
    "88": "Safety net/guard rail damaged or missing (under 6 stories)",
    "89": "Crane/derrick/suspension accident",
    "90": "Unlicensed/illegal activity",
    "91": "Site conditions endangering workers",
    "92": "Illegal conversion of manufacturing/industrial space",
    "93": "Retaining wall safety inspection requested",
    "94": "Defective/leaking plumbing, not maintained",
    "95": "Bronx 2nd offense pilot project",
    "96": "Unlicensed boiler/electrical/plumbing/sign work completed",
    "97": "Other agency jurisdiction",
    "98": "Referred to Operations for determination",
    "99": "Other",
}


def describe_complaint_category(code) -> str:
    code_str = str(code).strip()
    return COMPLAINT_CATEGORY_LABELS.get(code_str, f"Complaint (category {code_str})")